apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: outline
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: outline
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::062109560346:role/outline-demo-eks-external-secrets-role
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: outline
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: outline/production
